### PR TITLE
Hw14 andrey lukashenko

### PR DESCRIPTION
**Pull request by andriiluka**
beta version :)

### CODE REVIEW

**Comment by ahonymous** [comment]
невде є що перевірити

**Comment by ahonymous** [comment]
Where are language locale and translation of world in mail list?

**Comment by andriiluka** [comment]
sorry. i'm working on it

**Comment by ahonymous** [comment]
I have an error when create a new user and login with him credentials on homepage.

Stack Trace
http://prntscr.com/e5zgqe

**Comment by andriiluka** [comment]
fixed this issue. thx for review

**Pull request closed without merging**
